pipeline {
    agent any
    environment { 
        Name = 'Amith'
        Location = 'Hyderabad'
    }
    stages {
        stage('Example') {
            steps {
                sh ('echo my name is: $Name')
                sh ('echo I am from: $Location')
            }
        }
    }
}
   
