pipeline {
     //to run the build on any agent
    //agent any
    // to run the build on specific agent, use label
    agent {
        label 'slave'
         }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
